routes/admin.php
        Route::post('{id}/remove', 'Admin\AssignKostValue\AssignKostValueController@postRemoveBenefit')->name('assign-kost-value.postDeleteBenefit');
        Route::post('verify', 'Admin\AssignKostValue\AssignKostValueController@verify');
    });

    Route::group(['prefix' => 'property-package', 'as' => 'property-package.'], function () {
        Route::post('/', 'Admin\Level\PropertyPackageController@store')->name('store');

        Route::get('/create', 'Admin\Level\PropertyPackageController@createView')->name('.create');
        Route::put('/{propertyContract}', 'Admin\Level\PropertyPackageController@update')->name('update');

        Route::get('/index-list', 'Admin\Level\PropertyPackageController@indexList');
        Route::get('/dropdown-list', 'Admin\Level\PropertyPackageController@getLevels')->name('dropdown-list');
        Route::post('add-property', 'Admin\Level\PropertyPackageController@addProperty')->name('add-property');
        Route::post('/property/new','Admin\Level\PropertyPackageController@storeProperty');
        Route::get('/search-owner/{phoneNumber}', 'Admin\Level\PropertyPackageController@searchOwnerByPhone');

        Route::get('/{designerId}/room-list', 'Admin\Level\PropertyPackageController@getRoomLists')
            ->where('designerId', '[0-9]+')
            ->name('room-list');

        Route::get('/kost-list/owner/{owner}/property/{property}', 'Admin\Level\PropertyPackageController@kostListAssignToProperty')
            ->name('kost-list-assign-to-property');

        Route::get('/kost-list/property/{property}/{propertyContract}', 'Admin\Level\PropertyPackageController@kostListByProperty')->name('kost-list-by-property');
        Route::get('/detail/{propertyContract}', 'Admin\Level\PropertyPackageController@getPropertyPackageDetail');

        Route::get('/{ownerId}/property-list', 'Admin\Level\PropertyPackageController@getOwnersUnmappedProperties')->name('owner-property-list');

        Route::post('/toggle-assign', 'Admin\Level\PropertyPackageController@toggleAssignment')->name('toggle-assignment');

        Route::post('/{designerId}/{propertyContractId}/assign-all-rooms', 'Admin\Level\PropertyPackageController@assignAllRooms')
            ->where('designerId', '[0-9]+')
            ->name('assign-all-rooms');

        Route::post('/{designerId}/{propertyContractId}/unassign-all-rooms', 'Admin\Level\PropertyPackageController@unassignAllRooms')
            ->where('designerId', '[0-9]+')
            ->name('unassign-all-rooms');

        Route::put('/terminate/{propertyContract}', 'Admin\Level\PropertyPackageController@terminate');
        Route::put('/property/remove/{propertyContract}', 'Admin\Level\PropertyPackageController@removeProperty');
        Route::delete('/{propertyContract}', 'Admin\Level\PropertyPackageController@destroy');

        // VIEW
        Route::get('/', 'Admin\Level\PropertyPackageController@index');
        Route::get('/create/{phone_number?}', 'Admin\Level\PropertyPackageController@createView')->name('.create');
        Route::get('/update/{propertyContractId}', 'Admin\Level\PropertyPackageController@updateView')->name('.update');
        Route::get('/{ownerId}/{propertyId}/{propertyContractId}/assign', 'Admin\Level\PropertyPackageController@assignView')->name('.assign');
        Route::get('/{propertyContract}', 'Admin\Level\PropertyPackageController@detailView')->name('.detail');
    });

    Route::group(['prefix' => 'point', 'as' => 'point.'], function () {
        Route::resource('activity', Admin\Point\ActivityController::class);
        Route::resource('room-group', Admin\Point\OwnerRoomGroupController::class);

        Route::get('setting', 'Admin\Point\SettingController@index')->name('setting.index');
        Route::post('setting/tnc', 'Admin\Point\SettingController@tnc')->name('setting.tnc');
        Route::post('setting/{point}/{activity}', 'Admin\Point\SettingController@post')->name('setting.post');

        Route::get('expiry', 'Admin\Point\ExpiryController@index')->name('expiry.index');
        Route::post('expiry/change', 'Admin\Point\ExpiryController@change')->name('expiry.change');

        Route::get('blacklist', 'Admin\Point\BlacklistController@index')->name('blacklist.index');
        Route::get('blacklist/create', 'Admin\Point\BlacklistController@create')->name('blacklist.create');
        Route::post('blacklist/store', 'Admin\Point\BlacklistController@store')->name('blacklist.store');
        Route::get('blacklist/{id}/toggle', 'Admin\Point\BlacklistController@toggle')->name('blacklist.toggle');
        Route::get('blacklist/{id}/delete', 'Admin\Point\BlacklistController@delete')->name('blacklist.delete');

        Route::resource('segment', Admin\Point\SegmentController::class);

        // Point User
        Route::get('user/index', 'Admin\Point\UserPointController@index')->name('user.index');
        Route::put('user/{pointUser}/update-adjust-point', 'Admin\Point\UserPointController@updateAdjustPoint')->name('user.updateAdjustPoint');
        Route::put('user/update-bulk-adjust', 'Admin\Point\UserPointController@updateBulkAdjustPoint')->name('user.updateBulkAdjustPoint');
        Route::put('user/{pointUser}/update-blacklist', 'Admin\Point\UserPointController@updateBlacklist')->name('user.updateBlacklist');
        Route::put('user/update-bulk-blacklist', 'Admin\Point\UserPointController@updateBulkBlacklist')->name('user.updateBulkBlacklist');

        Route::get('history/{user}', 'Admin\Point\HistoryController@index')->name('history.index');
    });

    Route::group(['prefix' => 'reward-loyalty', 'as' => 'reward-loyalty.'], function () {
        Route::resource('type', Admin\RewardLoyalty\RewardTypeController::class);

        Route::get('list/{reward}/history', 'Admin\RewardLoyalty\RewardListController@rewardHistory')->name('list.history');
        Route::get('list/{reward}/redeem/{id}/history', 'Admin\RewardLoyalty\RewardListController@redeemHistory')->name('list.redeem.history');
        Route::put('list/{reward}/update-redeem-status/{id}', 'Admin\RewardLoyalty\RewardListController@updateRedeemStatus')->name('list.updateRedeemStatus');

        Route::group(['prefix' => 'list/{reward}/targeted-user', 'as' => 'list.targeted-user.'], function () {
            Route::put('remove', 'Admin\RewardLoyalty\RewardTargetedUserController@remove')->name('remove');
        });

        Route::resource('list', Admin\RewardLoyalty\RewardListController::class)->parameters([
            'list' => 'reward'
        ]);
    });

    // Polling
    Route::group(['prefix' => 'polling', 'as' => 'polling.'], function () {
        Route::resource('question', Admin\Polling\PollingQuestionController::class);
        Route::resource('option', Admin\Polling\PollingOptionController::class);
        Route::get('user/index', 'Admin\Polling\UserPollingController@index')->name('user.index');
    });
    Route::resource('polling', Admin\Polling\PollingController::class);

    Route::resource('promoted', Admin\PromotedController::class);
    Route::get('delete/{id}', ['as' => 'promoted.remove', 'uses' => 'Admin\PromotedController@destroy']);
    Route::post('promoted/search', 'Admin\PromotedController@searchName');
    Route::resource('recommendation', Admin\RecommendationController::class);

    // Route::get('owner/check-old-name', 'Admin\OwnerController@checkOldNameKos');
    // Route::group(['prefix' => 'owner'], function () {
    //     Route::get("popup/destroy/{id}", "Admin\Popup\PopupController@destroy");
    //     Route::resource('popup', 'Admin\Popup\PopupController');
    // });

    Route::get('igen', ['as' => 'igen', 'uses' => 'Admin\OwnerController@agenOwner']);

    Route::group(['prefix' => 'owner'], function () {
        // Route::resource('owner', 'Admin\OwnerController');
        Route::get('/', ['as' => 'owner.index', 'uses' => 'Admin\OwnerController@index']);
        Route::get('check-old-name', 'Admin\OwnerController@checkOldNameKos');
        Route::get("popup/destroy/{id}", "Admin\Popup\PopupController@destroy");
        Route::resource('popup', 'Admin\Popup\PopupController');
        Route::get('room', 'Admin\OwnerController@bookingRoom');
        Route::post('search', ['as' => 'owner.search', 'uses' => 'Admin\OwnerController@index']);
        Route::get('room/{phone}', 'Admin\OwnerController@kostOwner');
        Route::get('delete/{id}', ['as' => 'owner.destroy', 'uses' => 'Admin\OwnerController@destroy']);
        Route::get('verify/{id}', ['as' => 'owner.verify', 'uses' => 'Admin\OwnerController@verify']);
        Route::get('unverify/{id}', ['as' => 'owner.unverify', 'uses' => 'Admin\OwnerController@unverify']);
        Route::get('setting/{id}', ['as' => 'owner.setting', 'uses' => 'Admin\OwnerController@settingOwner']);
        Route::get('setting/{any}/{id}', ['as' => 'owner.setting', 'uses' => 'Admin\OwnerController@settingOwnerNotif']);
        Route::get('reject-remark/{id}', 'Admin\OwnerController@editRejectRemark')->name('owner.reject.edit');
        Route::post('reject-remark', 'Admin\OwnerController@updateRejectRemark')->name('owner.reject.update');
        Route::get('change/{id}', ['as' => 'owner.change', 'uses' => 'Admin\OwnerController@changeOwner']);
        Route::post('change/{id}', ['as' => 'owner.change', 'uses' => 'Admin\OwnerController@updateRoomOwner']);
        Route::get('agen/{id}', 'Admin\OwnerController@changeToOwnerPage');

        Route::group(['prefix' => 'data', 'as' => 'owner.data.'], function () {
            Route::group(['prefix' => 'kos', 'as' => 'kos.'], function () {
                Route::group(['prefix' => 'address','as' => 'address.'], function() {
                    Route::get('province', 'Api\Owner\Data\Address\ProvinceController@index')->name('list-province');
                    Route::get('city' , 'Api\Owner\Data\Address\CityController@index')->name('list-city');

routes/web.php
        // Balance and History Transaction
        // Route::get('/saldo', 'Api\UserWalletController@getBalance');
        // Route::post('withdraw', 'Api\UserWalletController@withdraw');
        // Route::get('transaction/invoice/history', 'Api\UserHistoryTransactionController@getHistoryInvoice');
        // Route::get('transaction/invoice/{invoiceId}', 'Api\UserHistoryTransactionController@getHistoryInvoiceDetail');
        // Route::get('transaction/{action}', 'Api\UserWalletController@getWalletHistory');
        // Route::get('transaction/{action}/{transactionId}', 'Api\UserWalletController@getWalletHistory');

        Route::get('booking/detail-room/{roomId}', 'Api\Booking\NewBookingUserController@detailRoom');
        Route::get('booking', 'Api\Booking\NewBookingUserController@index');
        Route::get('booking/detail/{bookId}', 'Api\Booking\NewBookingUserController@show');
        Route::post('booking/cancel/{bookId}', 'Api\Booking\NewBookingUserController@cancelBook');
        Route::post('booking/{roomId}/{roomType}', 'Api\Booking\NewBookingUserController@store');

        Route::get('booking/contract/{contractId}', 'Api\Booking\BookingContractController@getContract');
        Route::post('booking/invoice/filter/year', 'Api\Booking\BookingContractController@filterInvoiceByYearFromExternal');
        Route::get('booking/invoice/payment-schedule/{invoiceId}', 'Api\Booking\BookingContractController@invoiceDetail');
        Route::get('booking/room', 'Api\Booking\BookingRoomUserController@getRoomWithContract');
        Route::get('booking/status', 'Api\Booking\BookingStatusController@getListStatus');

        // Rent Count
        Route::get('booking/rent-count/{type}', 'Api\Booking\BookingRentCountController@getRentCount');
        Route::get('booking/rent-count/{type}/room/{roomId}', 'Api\Booking\BookingRentCountController@getRentCountByRoom');
        // Estimate Checkout
        Route::post('booking/estimate-checkout', 'Api\Booking\BookingRentCountController@getCheckoutDate');

        // draft-booking
        Route::get('draft-booking/shortcut', 'Api\Booking\BookingUserDraftController@homepageShortcut');
        Route::get('draft-booking/last-seen', 'Api\Booking\BookingUserDraftController@roomHistoryViewed');
        Route::delete('draft-booking/last-seen/{roomId}', 'Api\Booking\BookingUserDraftController@destroyViewedRoom');
        Route::get('draft-booking/notification', 'Api\Booking\BookingUserDraftController@notification');
        Route::resource('draft-booking', 'Api\Booking\BookingUserDraftController', ['only' => ['index', 'store', 'destroy']]);
        Route::resource('contract', 'Api\Contract\ContractUserController', ['only' => ['index', 'show']]);

        // contract link
        Route::get('contract-submission/onboarding', 'Api\Contract\ContractUserSubmissionController@onboarding');
        Route::get('contract-submission/shortcut', 'Api\Contract\ContractUserSubmissionController@homepageShortcut');
        Route::get('contract-submission/link/{code}', 'Api\Contract\ContractUserSubmissionController@showLink');
        Route::resource('contract-submission', 'Api\Contract\ContractUserSubmissionController', ['only' => ['store']]);

        // booking draft price
        Route::get('booking/draft-price/{songId}', 'Api\Booking\BookingDraftPriceController@index');

        // Point User
        Route::group(['prefix' => 'point'], function () {
            Route::get('total', 'Api\PointUserController@total');
            Route::get('expiry', 'Api\PointUserController@expiry');
            Route::get('tnc', 'Api\PointUserController@tnc');
            Route::get('activity', 'Api\PointUserController@activity');
            Route::get('history', 'Api\PointUserController@history');
            Route::get('scheme', 'Api\PointUserController@scheme');
        });

        // Polling
        Route::group(['prefix' => 'polling'], function () {
            Route::get('detail/{key}', 'Api\UserPollingController@detail');
            Route::post('submit/{key}', 'Api\UserPollingController@submit');
        });
        
        // Redeem
        Route::get('/redeem/list', 'Api\RewardController@userRedeemList');
        Route::get('/redeem/detail/{id}', 'Api\RewardController@userRedeemDetail')->where('id', '[0-9]+');
    });

    Route::group(['prefix' => 'stories'], function () {
        Route::post('cluster', 'Api\RoomController@listCluster');
        Route::post('list', 'Api\RoomController@listSearch')->middleware('web');
        Route::post('list2', 'Api\PropertySearchController@searchKost')->middleware('web');
        Route::get('facility/{type?}', 'Api\TagController@getFacilities');
        Route::get('filters', 'Api\TagController@getFacilitiesFilter');
        Route::post('filters/count', 'Api\RoomFilterController@countFilteredRooms');
        Route::post('landing/view/{id}', 'Api\LandingController@viewCount');
        Route::post('search_alarm', 'Api\SubscribeController@subscribeFilter');
        Route::post('subscribe_suggestion', 'Api\SubscribeController@subscribeFilter')->middleware('web');
        Route::post('subscribe_download', 'Api\RoomController@subscribeDownload')->middleware('web');
        Route::post('subscribe_download/update', 'Api\RoomController@subscribeDownloadUpdate')->middleware('web');

        Route::get('love', 'Api\RoomController@listFavorite')->middleware('web');
        Route::get('survey', 'Api\RoomController@listSurvey')->middleware('web');
        Route::get('telp', 'Api\RoomController@listTelp')->middleware('web');
        Route::get('call', 'Api\RoomController@listCall')->middleware('web');
        Route::get('view', 'Api\RoomController@listView')->middleware('web');
        Route::group(['prefix' => 'chat'], function () {
            Route::get('list', 'Api\Chat\ChatController@list');
            Route::post('tnc-tracker', 'Api\Chat\ChatTncTrackerController@store')->middleware('web');
        });

        Route::get('{id}', 'Api\RoomController@show');
        Route::get('{id}/photos', 'Api\RoomController@getCardsBySongId');
        Route::get('{id}/gallery', 'Api\Card\CardController@getCardsWithCategory');

        Route::post('{id}/call', 'Api\RoomController@postCall')->middleware('web');

        // Facility detail page :: used on API v1.7.2
        Route::get('facility/photos/{id}', 'Web\RoomFacilityController@getDetails');

        Route::get('location/{id}', 'Api\RoomController@getRoomLocation');

        Route::post('save_json_id', 'Api\RoomController@postSubmitKost');
        Route::post('input', 'Api\PropertyInputController@inputKost')->middleware('web');
        Route::post('input-simple', 'Api\PropertyInputController@inputKostSimple')/*->middleware('web')*/;
        Route::post('input-referral', 'Api\PropertyInputController@inputKostReferral')->middleware('web');
        Route::post('input-general', 'Api\PropertyInputController@inputKostGeneral')->middleware('web');
        Route::get('input/tags/{type}', 'Api\PropertyInputController@getTagsGroup');

        Route::post('{id}/love', 'Web\Api\RoomController@postFavorite')->middleware('web');
        Route::post('{id}/chat', 'Api\RoomController@postChat')->middleware('web');
        Route::post('{id}/chat/reply', 'Web\RoomController@postChatReply')->middleware('web');
        Route::post('{id}/view', 'Api\RoomController@postView')->middleware('web');

        Route::get('{id}/report', 'Api\OwnerController@getRoomReportOwner');

        Route::post('survey/add', 'Api\SurveyController@postSurvey')->middleware('web');
        Route::get('{id}/survey', 'Api\SurveyController@getSurvey')->middleware('web');

        Route::group(['prefix' => 'review', 'middleware' => 'web'], function () {
            Route::post('add', 'Api\ReviewController@addNewReview');
            Route::post('reply', 'Api\ReviewController@replyThread');
            Route::get('reply/{id}', 'Api\ReviewController@listRepltThread');
            Route::get('{id}', 'Web\ReviewController@getList');
        });

        // use flag term to send report about unmatched data
        Route::get('flag/type', 'Api\ReportController@reportType');
        Route::post('{id}/flag', 'Api\ReportController@postReport')->middleware('web');

        Route::group(['prefix' => 'house_property'], function () {
            Route::post('list', 'Api\HouseProperty\HousePropertyController@listSearch');
            Route::post('cluster', 'Api\HouseProperty\HousePropertyController@postCluster');
            Route::post('cluster/list', 'Api\HouseProperty\HousePropertyController@postClusterList');
            Route::post('{id}/call', 'Api\HouseProperty\HousePropertyController@postCall')->middleware('web');
            Route::post('{id}/chat/reply', 'Api\HouseProperty\HousePropertyController@postChatReply')->middleware('web');
            Route::get('{type}/{song_id}', 'Api\HouseProperty\HousePropertyController@detail');
        });

        Route::post('booking', 'Api\BookingController@postBooking')->middleware('web');

        Route::post('addreview', 'Api\ReviewController@postReview')->middleware('web');
        Route::post('updatereview', 'Api\ReviewController@updateReview')->middleware('web');
        Route::post('replyreview', 'Api\ReviewController@replyReview')->middleware('web');
        Route::get('{id}/getreview', 'Api\ReviewController@getReview')->middleware('web');

        Route::post('exist', 'Api\PropertyInputController@checkExistingInput');
        Route::get('exist/photo/{id}', 'Api\PropertyInputController@checkExistingPhoto');

        Route::group(['prefix' => 'review', 'middleware' => 'web'], function () {
            Route::post('reply', 'Api\ReviewController@replyThread');
            Route::get('reply/{id}', 'Api\ReviewController@listRepltThread');
            Route::get('{id}', 'Web\ReviewController@getList');
        });

        // old version to get recommendation rooms in detail page

resources/views/admin/contents/point/activity/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">{{ $boxTitle }}</h3>
        </div>

        @php
            $item = null;
            if (isset($activity)) {
                $route = URL::route('admin.point.activity.update', [$activity->id]);
                $item = $activity;
            } else {
                $route = URL::route('admin.point.activity.store');
            }
        @endphp
        <form action="{{ $route }}" method="POST" class="form-horizontal form-bordered">
            @if (isset($activity))
                <input type="hidden" name="_method" value="PUT">
            @endif
            
            <div class="box-body no-padding">
                <div class="form-group bg-default">
                    <label for="activity-key" class="control-label col-sm-2">Key</label>
                    <div class="col-sm-10">
                        <input type="text" name="key" id="activity-key" class="form-control" value="{{ old('key', optional($item)->key) }}">
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-name" class="control-label col-sm-2">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" id="activity-name" class="form-control" value="{{ old('name', optional($item)->name) }}">
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-target" class="control-label col-sm-2">Target</label>
                    <div class="col-sm-2">
                        <select name="target" id="activity-target" class="form-control">
                            @foreach ($target as $targetItem)
                            <option value="{{ $targetItem }}" @if (old('order', optional($item)->target) == $targetItem) selected="true" @endif>{{ $targetItem }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-title" class="control-label col-sm-2">Title</label>
                    <div class="col-sm-10">
                        <input type="text" name="title" id="activity-title" class="form-control" value="{{ old('title', optional($item)->title) }}">
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-description" class="control-label col-sm-2">Description</label>
                    <div class="col-sm-10">
                        <textarea name="description" id="activity-description" class="form-control" rows="4">{{ old('description', optional($item)->description) }}</textarea>
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-sequence" class="control-label col-sm-2">Sequence/Order</label>
                    <div class="col-sm-10">
                        <input type="number" name="sequence" id="activity-sequence" class="form-control" min="0" max="100" value="{{ old('sequence', optional($item)->sequence) }}">
                    </div>
                </div>

                <div class="form-group bg-default">
                    <label for="activity-status" class="control-label col-sm-2">Status</label>
                    <div class="col-sm-2">
                        @php
                            $disabled = ($ownerReceivedPaymentGeneralAvailable && in_array(optional($item)->key, $nonGeneralOwnerReceivedPaymentActivities));
                        @endphp
                        <select name="is_active" id="activity-status" class="form-control" @if ($disabled) disabled @endif>
                            <option value="1" @if (old('is_active', optional($item)->is_active) == '1') selected="true" @endif>Active</option>
                            <option value="0" @if (old('is_active', optional($item)->is_active) == '0') selected="true" @endif>Inactive</option>
                        </select>
                    </div>
                </div>

                <div class="form-group bg-default">
                    <div class="col-sm-10 col-sm-push-2">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

@section('style')
    <link rel="stylesheet" href="/assets/vendor/summernote/summernote.css?v=05042018">
@endsection

@section('script')
    <script src="/assets/vendor/summernote/summernote.min.js"></script>
    <script>
        $('#activity-description').summernote({
            height: 200,
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', []],
                ['color', ['color']],
                ['para', ['ul', 'ol']],
                ['insert', ['link']],
                ['misc', ['codeview']]
            ]
        });
    </script>
@endsection

resources/views/admin/contents/point/activity/index.blade.php
@extends('admin.layouts.main')

@section('content')
	<div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">{{ $boxTitle }}</h3>
        </div>

        <div class="box-body no-padding">
            <div class="horizontal-wrapper">
                <div class="btn-horizontal-group bg-default form-inline">
                    <div class="col-md-6 bg-default" style="padding-bottom:10px;">
                        <a href="{{ URL::route('admin.point.activity.create', ['#point']) }}" class="btn btn-primary">
                            <i class="fa fa-plus">&nbsp;</i>Add Activty
                        </a>
                    </div>
                    <div class="col-md-6 bg-default" style="padding-bottom:10px;text-align:right;">
                        <form action="" method="GET">
                            <input type="text" name="q" class="form-control"  placeholder="Activity Key"  autocomplete="off" value="{{ request()->input('q') }}">
                            <select name="t" class="form-control">
                                <option value="">All</option>
                                <option value="owner" {{request('t') == 'owner' ? 'selected' : ''}}>Owner</option>
                                <option value="tenant" {{request('t') == 'tenant' ? 'selected' : ''}}>Tenant</option>
                            </select>
                            <select name="s" class="form-control">
                                <option value="">All</option>
                                <option value="1" {{request('s') == '1' ? 'selected' : ''}}>Active</option>
                                <option value="0" {{request('s') == '0' ? 'selected' : ''}}>Inactive</option>
                            </select>
                            <button type="submit" class="btn btn-primary" id="buttonSearch">
                                <i class="fa fa-search">&nbsp;</i>Search
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <table  class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Key</th>
                        <th>Name</th>
                        <th>Title</th>
                        <th>Target</th>
                        <th>Status</th>
                        <th>Order</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($activity as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->key }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->title ?: '-' }}</td>
                        <td>
                            @if ($item->target === 'owner')
                                &nbsp;<span class="label label-success">OWNER</span>
                            @elseif ($item->target === 'tenant')
                                &nbsp;<span class="label label-primary">TENANT</span>
                            @else
                                -
                            @endif
                        </td>
                        <td>
                            @if ($item->is_active)
                                Active
                            @else
                                Inactive
                            @endif
                        </td>
                        <td><span class="badge badge-default">{{ $item->sequence ?: 0 }}</span></td>
                        <td>
                            <a href="{{ URL::route('admin.point.activity.edit', [$item->id, '#point']) }}" title="Edit" style="margin-right: 10px;">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <form action="{{ URL::route('admin.point.activity.destroy', [$item->id]) }}" method="POST" style="display: inline;">
                                <input type="hidden" name="_method" value="DELETE">
                                <a href="#" onclick="if(!confirm('Are you sure want to delete activity {{ $item->name }}?')) return false; else $(this).parent().submit();" title="Delete">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </form>
                        </td>
                    </tr> 
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="box-body no-padding">
            <div class="col-md-12 bg-default">
                {{ $activity->appends(Request::except('page'))->links() }}
            </div>
        </div>
    </div>
@endsection