routes/admin.php
    Route::get('area-big-mapper/{id}/destroy', ['as' => 'area-big-mapper.destroy', 'uses' => 'Admin\AreaBigMapperController@destroy']);
    Route::get('area-big-mapper/{id}/sync', ['as' => 'area-big-mapper.sync', 'uses' => 'Admin\AreaBigMapperController@sync']);
    Route::post('area-big-mapper/{id}/update-landing', ['as' => 'area-big-mapper.update-landing', 'uses' => 'Admin\AreaBigMapperController@updateAssociateLanding']);
    Route::post('area-big-mapper/landing-suggestion', 'Admin\AreaBigMapperController@landingSuggestion');

    Route::post('area-big-mapper/suggestion-city-regency', 'Admin\AreaBigMapperController@suggestionCityRegency');

    Route::get('area-big-mapper/remove-landing/{landing_id}', 'Admin\AreaBigMapperController@removeAssociateLanding');
    Route::post('area-big-mapper/{id}/update-landing-apartment', ['as' => 'area-big-mapper.update-landing-apartment', 'uses' => 'Admin\AreaBigMapperController@updateAssociateLandingApartment']);
    Route::post('area-big-mapper/landing-suggestion-apartment', 'Admin\AreaBigMapperController@landingSuggestionApartment');
    Route::get('area-big-mapper/remove-landing-apartment/{landing_id}', 'Admin\AreaBigMapperController@removeAssociateLandingApartment');
    Route::post('area-big-mapper/{id}/update-landing-jobs', ['as' => 'area-big-mapper.update-landing-jobs', 'uses' => 'Admin\AreaBigMapperController@updateAssociateLandingJobs']);
    Route::post('area-big-mapper/landing-suggestion-jobs', 'Admin\AreaBigMapperController@landingSuggestionJobs');
    Route::get('area-big-mapper/remove-landing-jobs/{landing_id}', 'Admin\AreaBigMapperController@removeAssociateLandingJobs');

    Route::resource('bank', Admin\BankController::class);
    Route::get('bank/destroy/{id}', 'Admin\BankController@destroy');
    Route::resource('premium/faq', Admin\PremiumFaqController::class);
    Route::resource('premium', Admin\PremiumController::class);

    Route::get('request/request/new', 'Admin\RequestController@newRequest');
    Route::post('request/request/new', 'Admin\RequestController@newPostRequest');
    Route::get('request/request/package', 'Admin\RequestController@packageList');
    Route::get('request/extend/{id}', 'Admin\RequestController@premiumExtendStatus');
    Route::resource('request', Admin\RequestController::class);
    Route::get('request/balance', 'Admin\RequestController@balance');
    Route::post('request/confirm/{id}', 'Admin\RequestController@confirmationuser');
    Route::get('request/confirmation/{id}', 'Admin\RequestController@confirmation');
    Route::get('request/balance/{id}', 'Admin\RequestController@destroyBalance');
    Route::get('request/deleted/{id}', 'Admin\RequestController@deleted');
    Route::get('request/kost/{id}', 'Admin\RequestController@kostOwner');
    Route::post('request/kost/{id}', 'Admin\RequestController@requestUpdate');
    Route::get('request/kost/{id}/allocation', 'Admin\RequestController@allocationFix');
    Route::get('request/kost/delete/{id}', 'Admin\RequestController@deleteRoomPromotion');

    Route::resource('premium-plus', Admin\Premium\PremiumPlusUserController::class);
    Route::get('premium-plus/{id}/invoice', 'Admin\Premium\PremiumPlusInvoiceController@index');
    Route::get('premium-cashback', 'Admin\Premium\PremiumCashbackController@index')->name('premium-cashback.index');

    Route::get('paket/recommendation/{id}', 'Admin\PaketController@recommendationChange');
    Route::resource('paket', Admin\PaketController::class);
    Route::get('paket/destroy/{id}', 'Admin\PaketController@destroy');

    Route::resource('click-pricing', Admin\ClickPricingController::class);
    Route::get('click-pricing/{id}/delete', ['as' => 'click-pricing.delete', 'uses' => 'Admin\ClickPricingController@destroy']);

    Route::resource('promo', Admin\PromoController::class);
    Route::get('promo/verify/{id}', 'Admin\PromoController@verifyWithButton');
    Route::get('promo/unverify/{id}', 'Admin\PromoController@unverifyPromo');
    Route::get('promo/delete/{id}', 'Admin\PromoController@delete');

    Route::resource('review', Admin\ReviewController::class);
    Route::get('review/deletephoto/{id}', 'Admin\ReviewController@deletePhoto');
    Route::resource('label', Admin\LabelController::class);
    Route::get('label/{id}/delete', ['as' => 'label.destroy', 'uses' => 'Admin\LabelController@destroy']);

    Route::resource('event', Admin\EventController::class);
    Route::get('event/publish/{id}', array('as' => 'event.publish', 'uses' => 'Admin\EventController@publish'));
    Route::get('event/search', array('as' => 'event.search', 'uses' => 'Admin\EventController@index'));
    Route::get('event/delete/{id}', array('as' => 'event.delete', 'uses' => 'Admin\EventController@destroy'));

    Route::group(['prefix' => 'notification-list'], function () {
        Route::get('category/order', 'Admin\Notification\CategoryController@orderList');
        Route::post('category/order', 'Admin\Notification\CategoryController@setOrder');
        Route::get('category/{id}/delete', 'Admin\Notification\CategoryController@destroy');
        Route::resource('category', Admin\Notification\CategoryController::class);
    });

    Route::group(['prefix' => 'kost-level'], function () {
        Route::resource('level', Admin\Level\KostLevelController::class);
        Route::post('kost-list/{id}/removeFlag', 'Admin\Level\KostListController@removeFlag');
        Route::get('kost-list/{id}/history', 'Admin\Level\KostListController@history');
        Route::get('kost-list/upload', 'Admin\Level\KostListController@upload');
        Route::post('kost-list/processCsv', 'Admin\Level\KostListController@processCsv');
        Route::resource('kost-list', Admin\Level\KostListController::class);
        Route::resource('faq', Admin\Level\FaqController::class);

        Route::resource('room-level', Admin\Level\RoomLevelController::class);
        Route::get('room-list/{id}', 'Admin\Level\RoomListController@index')->name('room-list.index');
        Route::put('room-list/{id}/room/{roomId}', 'Admin\Level\RoomListController@update')->name('room-list.update');
        Route::get('room-list/{id}/room/{roomId}/edit', 'Admin\Level\RoomListController@edit')->name('room-list.edit');
        Route::get('room-list/{id}/room/{roomId}/history', 'Admin\Level\RoomListController@history')->name('room-list.history');
        Route::post('room-list/{id}/assignall', 'Admin\Level\RoomListController@assignAll')->name('room-list.assignall');
    });

    // Kost Value Management
    Route::group(['prefix' => 'kost-value'], function () {
        Route::get('/', 'Admin\KostValue\KostValueController@index')->name('kost-value.index');
        Route::get('add', 'Admin\KostValue\KostValueController@create')->name('kost-value.create');
        Route::post('add', 'Admin\KostValue\KostValueController@store')->name('kost-value.store');
        Route::get('edit/{id}', 'Admin\KostValue\KostValueController@edit')->name('kost-value.edit');
        Route::post('edit/{id}', 'Admin\KostValue\KostValueController@update')->name('kost-value.update');
        Route::post('remove', 'Admin\KostValue\KostValueController@remove')->name('kost-value.remove');
        Route::get('values', 'Admin\KostValue\KostValueController@getValues')->name('kost-value.values');
    });

    // Assign Benefit to kost
    Route::group(['prefix' => 'assign-kost-value'], function () {
        Route::get('/', 'Admin\AssignKostValue\AssignKostValueController@index')->name('assign-kost-value.index');
        Route::get('{id}/edit', 'Admin\AssignKostValue\AssignKostValueController@create')->name('assign-kost-value.create');
        Route::post('{id}/edit', 'Admin\AssignKostValue\AssignKostValueController@postAddBenefit')->name('assign-kost-value.postAddBenefit');
        Route::get('data', 'Admin\AssignKostValue\AssignKostValueController@getAllData')->name('assign-kost-value.all');
        Route::post('{id}/remove', 'Admin\AssignKostValue\AssignKostValueController@postRemoveBenefit')->name('assign-kost-value.postDeleteBenefit');
        Route::post('verify', 'Admin\AssignKostValue\AssignKostValueController@verify');
    });

    Route::group(['prefix' => 'property-package', 'as' => 'property-package.'], function () {
        Route::post('/', 'Admin\Level\PropertyPackageController@store')->name('store');

        Route::get('/create', 'Admin\Level\PropertyPackageController@createView')->name('.create');
        Route::put('/{propertyContract}', 'Admin\Level\PropertyPackageController@update')->name('update');

        Route::get('/index-list', 'Admin\Level\PropertyPackageController@indexList');
        Route::get('/dropdown-list', 'Admin\Level\PropertyPackageController@getLevels')->name('dropdown-list');
        Route::post('add-property', 'Admin\Level\PropertyPackageController@addProperty')->name('add-property');
        Route::post('/property/new','Admin\Level\PropertyPackageController@storeProperty');
        Route::get('/search-owner/{phoneNumber}', 'Admin\Level\PropertyPackageController@searchOwnerByPhone');

        Route::get('/{designerId}/room-list', 'Admin\Level\PropertyPackageController@getRoomLists')
            ->where('designerId', '[0-9]+')
            ->name('room-list');

        Route::get('/kost-list/owner/{owner}/property/{property}', 'Admin\Level\PropertyPackageController@kostListAssignToProperty')
            ->name('kost-list-assign-to-property');

        Route::get('/kost-list/property/{property}/{propertyContract}', 'Admin\Level\PropertyPackageController@kostListByProperty')->name('kost-list-by-property');
        Route::get('/detail/{propertyContract}', 'Admin\Level\PropertyPackageController@getPropertyPackageDetail');

        Route::get('/{ownerId}/property-list', 'Admin\Level\PropertyPackageController@getOwnersUnmappedProperties')->name('owner-property-list');

        Route::post('/toggle-assign', 'Admin\Level\PropertyPackageController@toggleAssignment')->name('toggle-assignment');

routes/web.php
            Route::post('facshare/{id}', 'Api\RoomUpdaterController@updateFacShare')->middleware('api.auth:user');
            Route::post('parking/{id}', 'Api\RoomUpdaterController@updateParking')->middleware('api.auth:user');
            Route::post('facnear/{id}', 'Api\RoomUpdaterController@updateFacNear')->middleware('api.auth:user');
            Route::post('otherinformation/{id}', 'Api\RoomUpdaterController@updateOtherInformation')->middleware('api.auth:user');
        });

        Route::group(['prefix' => 'edit'], function () {
            Route::get('name/{id}', 'Api\RoomUpdaterController@getNameType')->middleware('api.auth:user');
            Route::get('price/{id}', 'Api\RoomUpdaterController@getPriceRoom')->middleware('api.auth:user');
            Route::get('size/{id}', 'Api\RoomUpdaterController@getRoomSize')->middleware('api.auth:user');
            Route::get('otherinformation/{id}', 'Api\RoomUpdaterController@getOtherInformation')->middleware('api.auth:user');
            Route::get('facnear/{id}', 'Api\RoomUpdaterController@getFacNear')->middleware('api.auth:user');
            Route::get('parking/{id}', 'Api\RoomUpdaterController@getParking')->middleware('api.auth:user');
            Route::get('facshare/{id}', 'Api\RoomUpdaterController@getFacShare')->middleware('api.auth:user');
            Route::get('facroom/{id}', 'Api\RoomUpdaterController@getFacRoom')->middleware('api.auth:user');
            Route::get('bathroom/{id}', 'Api\RoomUpdaterController@getBathroom')->middleware('api.auth:user');
        });

        Route::group(['prefix' => 'jobs'], function () {
            Route::group(['prefix' => 'company'], function () {
                Route::post('list', 'Api\Jobs\Company\ProfileController@postListCompanyProfile');
                Route::get('detail/{slug}', 'Api\Jobs\Company\ProfileController@getDetailProfile');
            });
            Route::post('add', 'Api\Jobs\JobsActionController@addNewJobs')->middleware('web');
            Route::post('cluster', 'Api\Jobs\JobsViewController@jobsListCluster');
            Route::group(['prefix' => 'cv', 'middleware' => 'web'], function () {
                Route::post('add', 'Api\Jobs\JobsActionController@addCv');
                Route::post('file', 'Api\Jobs\JobsActionController@addFile');
            });

            Route::post('landing/view/{id}', 'Api\Jobs\JobsViewController@viewCount');

            Route::post('list', 'Api\Jobs\JobsViewController@jobsListSearch')->middleware('web');

            Route::get('landing/{slug}', 'Api\Jobs\JobsActionController@getLandingJobs');
            Route::get('{slug}', 'Web\Vacancy\VacancyController@detailJobs')->middleware('web');
            Route::post('list/cluster', 'Api\Jobs\JobsViewController@singleCluster');

            Route::group(['prefix' => 'edit', 'middleware' => 'web'], function () {
                Route::get('{id}', 'Api\Jobs\JobsActionController@editData');
                Route::post('{id}', 'Api\Jobs\JobsActionController@postEditData');
                Route::get('edit/{id}', 'Api\Jobs\JobsViewController@getDataCV');
                Route::post('update/{id}', 'Api\Jobs\JobsActionController@updateCv');
            });
            Route::post('verification', 'Api\Jobs\JobsActionController@verificationFromUser');
        });

        Route::group(['prefix' => 'subscribe'], function () {
            Route::get('content', 'Web\LandingContentController@getContent');
        });

        // Room meta for chat feature
        // Ref task: https://mamikos.atlassian.net/browse/BG-524
        Route::get('meta/{id}', 'Api\RoomMetaController@getRoomMeta');

        Route::get('nearby/{id}', 'Api\RoomController@getNearbyBySongId')->middleware('api.auth:device');
    });

    //Kost Level
    Route::group(['prefix' => 'kost-level', 'middleware' => 'web'], function () {
        Route::get('info', 'Api\KostLevelController@index');
        Route::post('{kostId}/approve', 'Api\KostLevelController@approve');
        Route::post('{kostId}/reject', 'Api\KostLevelController@reject');
        Route::post('{kostId}/ack', 'Api\KostLevelController@ack');
    });

    Route::group(['prefix' => 'room'], function () {
        Route::post('list/cluster', 'Api\RoomController@detailCluster')->middleware('web');

        // get Room Type Number
        Route::get('type/{roomTypeId}/number', 'Api\RoomController@getRoomTypeNumber');
    });

    Route::group(['prefix' => 'apartment'], function () {
        Route::get('landing/{slug}', 'Api\LandingApartmentController@show');

        Route::get('project-tags', 'Api\PropertyInputController@getApartmentProjectTags');
        Route::post('suggestion/name', 'Api\ApartmentProjectController@suggestions');
        Route::post('input', 'Api\PropertyInputController@inputApartment')->middleware('web');
        Route::post('request-input', 'Api\PropertyInputController@requestInputPost');

        Route::post('landing/view/{id}', 'Api\LandingApartmentController@viewCount');

        Route::get('project', 'Api\ApartmentProjectController@show');
        Route::post('project/list/{id}/{code}', 'Api\ApartmentController@listApartmentByProject');

        Route::post('list', 'Api\ApartmentProjectController@listSearch');
        Route::post('list/cluster', 'Api\ApartmentProjectController@detailCluster');
        Route::post('cluster', 'Api\ApartmentProjectController@clusterSearch');
    });

    Route::group(['prefix' => 'owner'], function () {
        Route::group(['prefix' => 'data', 'middleware' => 'web'], function () {
            Route::get('profile', 'Api\OwnerDataController@getProfile');
            Route::get('notification', 'Api\OwnerDataController@getNotificationOwner');

            Route::group(['prefix' => 'kos', 'as' => 'kos.'], function () {
                Route::get('/', 'Api\OwnerDataController@getOwnedKos')->name('iklan-saya');
                
                Route::group(['prefix' => 'room-unit', 'as' => 'allotment.'], function() {
                    Route::get('/', 'Api\Room\RoomUnitController@index')->name('index');
                    Route::group(['prefix' => 'single', 'as' => 'single.'], function() {
                        Route::post('/', 'Api\RoomAllotment\RoomAllotmentController@addRoomUnit')->name('add');
                        Route::put('{id}', 'Api\RoomAllotment\RoomAllotmentController@editRoomUnit')->name('update');
                        Route::delete('{id}', 'Api\RoomAllotment\RoomAllotmentController@deleteRoomUnit')->name('delete');
                    });
                    Route::post(
                        'bulk',
                        'Api\RoomAllotment\RoomAllotmentController@updateBulkRoomUnit'
                    )->name('update-bulk');
                });
            });
            Route::group(['prefix' => 'list'], function () {
                Route::get('update', 'Api\OwnerDataController@getListKosForUpdate');
                Route::get('kos', 'Api\OwnerDataController@getListKos');
                Route::get('kos/{id}', 'Api\OwnerDataController@detailKosOwner');
                Route::get('apartment', 'Api\OwnerDataController@getListApartment');
                Route::get('apartment/{id}', 'Api\OwnerDataController@detailKosOwner');
                Route::get('active', 'Api\OwnerDataController@getListAllCanPromote');
                Route::get('jobs', 'Api\Jobs\JobsViewController@ownerList');
                Route::group(['prefix' => 'jobs'], function () {
                    Route::group(['prefix' => 'apply'], function () {
                        Route::get('jobs/{id}', 'Api\Jobs\JobsViewController@getListApply');
                        Route::get('{id}', 'Api\Jobs\JobsViewController@detailApply');
                    });
                    Route::get('{slug}/report', 'Api\Jobs\JobsViewController@ownerJobsReport');
                    Route::get('{slug}/deactive', 'Api\Jobs\JobsActionController@deactiveJobsOwner');
                    Route::get('{slug}/active', 'Api\Jobs\JobsActionController@activeJobsOwner');
                    Route::get('{slug}/delete', 'Api\Jobs\JobsActionController@deleteJobsOwner');
                    Route::get('{slug}', 'Api\Jobs\JobsViewController@ownerJobsDetail');
                });
            });
            Route::group(['prefix' => 'survey'], function () {
                Route::post('updateroom', 'Api\OwnerDataController@surveyUpdateRoom');
                Route::post('premium', 'Api\OwnerDataController@surveyPremium');
            });
            Route::group(['prefix' => 'booking'], function () {
                Route::get('/', 'Api\Booking\Owner\BookingController@getListData');
            });
            Route::group(['prefix' => 'kost-level'], function () {
                Route::get('flag-count', 'Api\KostLevelController@flagCount');
                Route::get('list', 'Api\KostLevelController@kostList');
            });

            Route::post('update-room', 'Api\OwnerDataController@updateAllProperty');
            Route::get('income', 'Api\OwnerDataController@getDashboardTotalIncome');
        });
        Route::group(['prefix' => 'edit'], function () {
            Route::post('email', 'Api\OwnerController@editEmail')->middleware('web');
            Route::post('name', 'Api\UserController@editName')->middleware('web');
            Route::post('phone', 'Api\Auth\OwnerController@editPhone')->middleware('web');
            Route::post('phone/request', 'Api\Auth\OwnerController@editPhoneRequest')->middleware('web');
        });
        Route::get('list', 'Api\OwnerController@getListOwner')->middleware('web');
        Route::post('room/save', 'Api\OwnerController@postSaveOwnerDesignerViaWeb')->middleware('web');
        Route::post('room/draft', 'Api\OwnerController@postSaveOwnerDesignerViaWeb')->middleware('web');
        Route::get('edit_room/{id}', 'Api\OwnerController@editRoomOwner')->middleware('web');

resources/views/admin/contents/paket/index.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- table -->
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">{{ $boxTitle }}</h3>
            <div class="box-tools pull-right">
                <a href="#"><i class="fa fa-minus" data-widget="collapse"></i></a>
                <a href="#"><i class="fa fa-times" data-widget="remove"></i></a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">

            <div class="horizontal-wrapper">
                <div class="btn-horizontal-group bg-default">
                    <a href="{{ URL::route('admin.paket.create') }}">
                        <button type="submit" class="btn-add btn btn-primary btn-sm">
                            <i class="fa fa-plus">&nbsp;</i>Tambah Paket Premium</button>
                    </a>
                    <form action="" class="form-inline" method="get" style="text-align:right;padding:10px;">
                        <input type="text" name="q" class="form-control input-sm"  placeholder="Nama paket"  autocomplete="off" value="{{ request()->input('q') }}" />
                        {{ Form::select('type', $packageType, request()->input('type'), array('class' => 'pull-right-sort form-group btn btn-primary btn-sm')) }}     
                        <button class="btn btn-primary btn-sm" id="buttonSearch"><i class="fa fa-search">&nbsp;</i>Search</button>
                  </form>
                </div>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="30px;">No</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Sale Price</th>
                        <th>Start - End Date</th>
                        <th>Days Count</th>
                        <th>is Active</th>
                        <th>Views</th>
                        <th>For</th>
                        <th class="table-action-column">Action</th>
                    </tr>
                </thead>
                <tbody>
                   @foreach ($PremiumPackage AS $key => $package)
                       <tr>
                           <td>{{ $key+1 }}</td>
                           <td>@if ($package->special_price > 0)
                             <i class="fa fa-star" title="Special price" aria-hidden="true"></i>
                           @endif
                           {{ $package->name }}</td>
                           <td>Rp {{ number_format($package->price,0,",",".") }}</td>
                           <td>Rp {{ number_format($package->sale_price,0,",",".") }}</td>
                           <td>{{ date('d M Y', strtotime($package->start_date)) }} <strong> - </strong> {{ date('d M Y', strtotime($package->sale_limit_date)) }}</td>
                           <td>{{ $package->total_day }}</td>
                           <td>@if ($package->is_active == '1')
                                  <span class="label label-success">Yes</span>
                               @else
                                  <span class="label label-danger">No</span>
                               @endif
                           </td>
                           <td>{{ $package->view }}</td>
                           <td>
                             @if ($package->for == 'balance')
                                  <span class="label label-info">Balance</span>
                             @elseif (in_array($package->for, ['package', 'apartment', 'kos'])) 
                                  <span class="label label-danger">Package</span>
                             @else
                                  <span class="label label-warning">Trial</span>     
                             @endif
                           </td>
                           <td><a href="{{ URL::route('admin.paket.edit', $package->id) }}"><i class="fa fa-pencil"></i></a>

                           @if (in_array($package->for, ['package', 'apartment', 'kos']))
                                
                               @if (date('Y-m-d', strtotime('-5 days', strtotime($package->sale_limit_date))) < date('Y-m-d') AND date('Y-m-d') <= $package->sale_limit_date)
                                  <span class="label label-warning">mau abs waktunya</span>
                               @elseif ($package->sale_limit_date < date('Y-m-d'))
                                  <span class="label label-danger">udh abs waktunya</span>
                               @else 
                                  <span class="label label-danger"></span>
                               @endif

                           @endif

                           @if ($package->is_recommendation == 1 AND $package->sale_limit_date >= date('Y-m-d'))
                                <a href="{{ URL::to('admin/paket/recommendation', $package->id) }}"><i style="color: #ff0000;" title="Is recommendation" class="fa fa-star"></i></a>
                           @elseif ($package->is_recommendation == 0 AND $package->sale_limit_date >= date('Y-m-d') AND $package->for != 'trial')
                                <a href="{{ URL::to('admin/paket/recommendation', $package->id) }}"><i style="color: #cccccc;" title="Is recommendation ?" class="fa fa-star"></i></a>
                           @endif
                               <!-- <a href="{{ URL::to('admin/paket/destroy', $package->id) }}"><i class="fa fa-trash-o"></i></a>
                            -->
                            
                         </td>
                       </tr>
                   @endforeach
                </tbody>
                
            </table>
            <div class="box-body no-padding">
                {{ $PremiumPackage->appends(Request::except('page'))->links() }}
            </div>
        </div><!-- /.box-body -->
    </div><!-- /.box -->
    <!-- table -->

@stop